# Generated by Django 3.2.25 on 2025-02-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
    ]
